# Generated by Django 5.2.6 on 2025-11-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0006_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='cliente_numero',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='lectura_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_asociado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente_numero',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='medidor_numero',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medidor',
            name='contrato_numero',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='boleta_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
